### ISSUE TITLE
Hide video course from clients who bought Mailcoach license

### ISSUE THREAD

**Issue by WouterBrouwers** [spatie/spatie.be#102]
I think we should not show the option to buy the Mailcoach videos to people who have already bought a license (because the videos are already included within a standard license). This will only confuse our clients. 

![image](https://user-images.githubusercontent.com/40539118/96095493-f025e800-0ece-11eb-8df7-78d4a6859a39.png)

**Comment by freekmurze** [comment]
Going to leave like it is now to avoid coding up complex per product rules for this.
