### ISSUE TITLE
YouTube + YouTube assets

### ISSUE THREAD

**Issue by WouterBrouwers** [spatie/spatie.be#104]
- add `YouTube` to footer
![image](https://user-images.githubusercontent.com/40539118/97456397-2173ce80-1939-11eb-95a5-f099f21145ba.png)

create YouTube assets for profile page: 
- 2560x1440 Spatie banner (cover for profile page)
- 800x800 profile picture with Spatie logo
- optional: Easy template to create thumbnail images (1280x720) for the videos
-> just to avoid all the thumbnails from looking the same. I'm thinking about the logo of the product + title of the video in the thumbnail?

**Comment by willemvb** [comment]
Closed via https://github.com/spatie/spatie.be/commit/9cd40f4abb6766f06e6ada3022f830da7c1b65a1
