### ISSUE TITLE
Server Error When Attempting To Connect To Ray Github

### ISSUE THREAD

**Issue by devingray** [spatie/spatie.be#134]
Hi. 

I just bought Ray and I see a link "Connect Github To Access Repo"

When I click it, it does a Github Callback and then redirects to server error page.

**Comment by freekmurze** [comment]
We were experiencing rate limiting issues. We have fixed some things at our end to avoid this.

The ray packages are also now public, so we don't have to explicitly add you to the repos anymore via the API.
