### ISSUE TITLE
Incorrect Link in the Ray Docs

### ISSUE THREAD

**Issue by manogi** [spatie/spatie.be#136]
Hi there,
I hope this is the right place for me to mention this:
On the page https://spatie.be/docs/ray/v1/usage/laravel I think the first link in the text should actually go to https://spatie.be/docs/ray/v1/usage/framework-agnostic-php-project, not https://spatie.be/docs/ray/v1/usage/in-a-framework-agnostic-project.

Thanks for all your cool stuff!

**Comment by manogi** [comment]
Oh, while I'm at it: The "position: sticky" on the navigation does not work so well for me on a MBP 16" (I have to scroll all the way down to see the last links):


https://user-images.githubusercontent.com/1419634/104322704-8c1eba00-54e5-11eb-833e-c7e2961e4765.mp4

**Comment by freekmurze** [comment]
Could you PR a fix for the link? There's an edit button on every page.

@willemvb could you take a look at the sticky position?

**Comment by manogi** [comment]
PR'd - did not know about that edit button.
