### ISSUE TITLE
Error if not logged in

### ISSUE THREAD

**Issue by bladerunner2021** [spatie/spatie.be#147]
I'm on the latest version of Laravel and Nova, if I do /mailcoach and I'm already logged in in Nova is it fine, but I see the menu as the attached screen.
![Schermata 2021-03-26 alle 17 43 22](https://user-images.githubusercontent.com/81435970/112669911-8b4cc180-8e60-11eb-94db-d32eb9e192b5.png)
If I'm not logged in I got this error:

Symfony\Component\Routing\Exception\RouteNotFoundException
Route [login] not defined.
Illuminate\Routing\UrlGenerator::route
vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:429

**Comment by freekmurze** [comment]
This one should go on spatie/laravel-mailcoach

**Comment by bladerunner2021** [comment]
I got a 404 not found for https://github.com/spatie/laravel-mailcoach
