### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'referrers.github_username' in 'where clause'...

### ISSUE THREAD

**Issue by freekmurze** [spatie/spatie.be#158]
**`Illuminate\Database\QueryException`**

Illuminate\Database\Connection::runQueryCallback
```php
676           // lot more helpful to the developer instead of just the database's errors.
677           catch (Exception $e) {
678*              throw new QueryException(
679                   $query, $this->prepareBindings($bindings), $e
680               );
```
*File: /home/forge/spatie.be/releases/20210414-143537/vendor/laravel/framework/src/Illuminate/Database/Connection.php*

[Open in Flare](https://flareapp.io/errors/462358/latest)

**Comment by freekmurze** [comment]
@riasvdv could you take a look at this one?

**Comment by riasvdv** [comment]
Seems like github_username is not in the referrers table, so it shouldn't be searchable in nova https://github.com/spatie/spatie.be/blob/master/app/Nova/Referrer.php#L23

I'll fix it this afternoon
