### ISSUE TITLE
Local currency prices with currency symbol are misleading

### ISSUE THREAD

**Issue by paras-malhotra** [spatie/spatie.be#162]
We ported some of your awesome code here onto Enlightn to display localized pricing. One issue that we faced was that it's not apparent that the pricing is in local currency.

So, for instance, when someone from the US visits your Ray product page, the price may show $49. If someone from Australia visits it, it shows $63. If someone from Hong Kong visits, it shows $292! It isn't clear that the $ represents USD, AUD and HKD respectively.

We've temporarily solved this issue by displaying a note (e.g. "prices displayed above are in HKD") below the pricing like so:

![pricing](https://user-images.githubusercontent.com/16099046/117203504-b5ed4b00-ae0c-11eb-9f37-ff43db0599df.png)

Just wanted to raise this issue in case you weren't already aware of it. Thanks once again for making your repo open source. It helped us a lot! ❤️ 

Sorry if issues were only meant for internal purposes. I didn't mean to intrude.

**Comment by freekmurze** [comment]
I'm happy that our code can help you.

Thanks for bringing this problem to our attention. It's a valid remark and we'll improve on it soon.
Feel free to suggested other improvements you might see.
