### ISSUE TITLE
Renewing multiple licenses at once doesn't work

### ISSUE THREAD

**Issue by WouterBrouwers** [spatie/spatie.be#171]
If you have multiple licenses (for example 2 mailcoach licenses), and you decide to purchase 2 renewals at once during the checkout process (because both licenses in your account are expired), then only one of the two licenses gets renewed (and the other one in your account will stay expired). 

user casenxu@exducereonline.com had this issue when he tried to renew two Mailcoach licenses at once.

**Comment by riasvdv** [comment]
Renewals won't have a "quantity" field once we deploy #191 so this should resolve itself, along with a clearer purchase management screen.
