### ISSUE TITLE
Laravel & PHP Guidelines styling is broken

### ISSUE THREAD

**Issue by adevade** [spatie/spatie.be#189]
The menu items break out of the sidebar, and nothing happens when you click the links.

Page: https://spatie.be/guidelines/laravel-php

Screenshot: ![image](https://user-images.githubusercontent.com/1066486/129212817-c22b54f9-e39a-48eb-be3d-2e7e9ae25b84.png)

**Comment by riasvdv** [comment]
Thanks for letting us know! The guidelines have been fixed
