### ISSUE TITLE
Redirect too many time

### ISSUE THREAD

**Issue by chengkangzai** [spatie/spatie.be#218]
Step to reproduce 

- Go to https://spatie.be/index.php/docs/laravel-query-builder/v5/introduction
- Click every link side menu (ps: noticed the URL show v3 but it should be v5)
- The browser will show redirect too many times.
![image](https://user-images.githubusercontent.com/43839286/149445345-b30b25af-fc81-4a46-a358-f26b12af1613.png)

ps: Thanks Spatie for all the packages 🙏

**Comment by freekmurze** [comment]
This has been fixed 👍

**Comment by mertasan** [comment]
@freekmurze same issue

![spatie](https://user-images.githubusercontent.com/13007665/151662673-342926de-280d-427a-a71e-a3f86bbe8be5.png)

https://github.com/spatie/spatie.be/blob/a43babb5a51b86b218b4ed98552ce55607ad3b3f/config/docs.php#L219

**Comment by freekmurze** [comment]
This issue is fixed.
