### ISSUE TITLE
🚀 Upgrade to Laravel 9

### ISSUE THREAD

**Issue by Nielsvanpach** [spatie/spatie.be#220]
**Missing L9 support**

* [x] [Laravel Nova](https://nova.laravel.com/releases)
* [x] https://github.com/spatie/schema-org/pull/176
* [x] https://github.com/spatie/sheets

**Has support on new major**

* [x] https://github.com/spatie/laravel-mailcoach/pull/875
* [x] https://github.com/spatie/laravel-enum
* [x] https://github.com/spatie/laravel-backup
* [x] https://github.com/spatie/laravel-event-sourcing
* [x] https://github.com/spatie/laravel-markdown
* [x] https://github.com/spatie/laravel-medialibrary
* [x] https://github.com/spatie/laravel-query-builder
* [x] https://github.com/spatie/laravel-schedule-monitor
* [x] https://github.com/spatie/laravel-webhook-client

**Other**

* [x] https://github.com/spatie/spatie.be/pull/221
* [x] https://github.com/spatie/spatie.be/pull/222 (ignition & flare)
* [x] https://github.com/spatie/laravel-model-cleanup => deprecated package, but still used in laravel-mailcoach

Upgrading guide: https://laravel.com/docs/master/upgrade

**Upgrades afterwards**

* [ ] Use Larastan v2 (has support for squashed migrations 🎉 )

**Comment by riasvdv** [comment]
Laravel model cleanup has been removed in Mailcoach v5 so I checked that one off as well
