### ISSUE TITLE
React Engineer vacancy assets

### ISSUE THREAD

**Issue by WouterBrouwers** [spatie/spatie.be#227]
I would like to have a Spatie themed image which we can use for the new React Engineer vacancy. 

We're going to publish it on the following platforms: 

- Facebook: 1200 x 630, JPG or PNG
- Linkedin: 1200 x 628, JPG or PNG
- Twitter:  1600 x 900 and 600 x 335, JPG or PNG
- Instagram: 1080 x 566 and 1080 x 1080, JPG or PNG

**Comment by vicdenys** [comment]
#Test

**Comment by vicdenys** [comment]
# test
## test
### test
#### Test
##### Test
###### Tst
