### ISSUE TITLE
Apple login is broken

### ISSUE THREAD

**Issue by jefvdv** [spatie/spatie.be#242]
Trying to login with Apple gets you an error:

<img width="1122" alt="Screenshot 2022-04-15 at 11 25 38" src="https://user-images.githubusercontent.com/19529388/163553812-a5bb143c-fa30-4dd2-b30d-4c5c3d4f7f83.png">

**Comment by riasvdv** [comment]
Fixed! 6 months go by fast https://github.com/spatie/spatie.be#apple-sign-in
