### ISSUE TITLE
Video instead of banner on product page

### ISSUE THREAD

**Issue by jefvdv** [spatie/spatie.be#246]
Would be nice to have the video intro over here instead of the static banner:
https://spatie.be/products/writing-readable-php

**Comment by jefvdv** [comment]
Showing the original (non-discount) price on this page is probably part of the new spatie.be?

**Comment by willemvb** [comment]
Exception made to show video on this detail page.

 I'm all in favor of consolidating promo sites / these product pages so we don't have to maintain everything twice.
Uniform price cards could also be part of this.
