### ISSUE TITLE
Good first issues link does not work on mobile

### ISSUE THREAD

**Issue by clnt** [spatie/spatie.be#27]
Hi!

Just noticed this odd issue with the "all easy issues on GitHub" link, when trying to access it on a mobile it does not work, I get a 404. However, it works fine once on a computer. It seems to be related to the quotation marks.

This is the link that is generated on a mobile: https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aspatie+is%3Apublic+label%3A%22good+first+issue%22

**Comment by freekmurze** [comment]
That link seems to be working on my mobile device (iPhone, Safari, iOS12 beta). 

What device are you using?

**Comment by clnt** [comment]
Hmm that is odd, I've just tried again and it still doesn't work. I have an iPhone 6s and have tested in Firefox + Safari

**Comment by clnt** [comment]
I noticed what was causing this, it is simply from not being logged into Github on the device/browser which the link opens in. Ideally Github should redirect to login rather than produce a 404.

Closing issue :)
