### ISSUE TITLE
Ray contest winners Povilas

### ISSUE THREAD

**Issue by WouterBrouwers** [spatie/spatie.be#272]
Povilas (https://spatie.be/nova/resources/users/8099) has bought 10 Ray licenses for his contest winners. 
All the licenses have been bought on the 28th of February. 

Can you assign a Ray license key to each of the winners? 

They already have a Spatie account: 
fmk@windowslive.com
potapdmitry16@gmail.com
mikecorporal@gmail.com
carloscrespo@gmail.com
galeapatrik@gmail.com
johnnnyjoe@gmail.com
zanette.marco90@gmail.com
rst630@gmail.com
matthias.hoffmann.app@gmail.com
dave@springbasemedia.com

**Comment by riasvdv** [comment]
Done!
