### ISSUE TITLE
Docs for image package not updated.

### ISSUE THREAD

**Issue by tvbeek** [spatie/spatie.be#287]
On the website I only see the documentation for v1 https://spatie.be/docs/image/v1/introduction

In the config I see 3 versions ( https://github.com/spatie/spatie.be/blob/main/config/docs.php#L224-L233 )

After reading the [blogpost from Freek](https://freek.dev/1795-selling-digital-products-using-laravel-part-7-importing-package-documentation-from-github) I guess that the webhook for https://github.com/spatie/image isn't set. (That package doesn't have a issue option, that is why I create the issue here)

**Comment by freekmurze** [comment]
This has been fixed 👍
