### ISSUE TITLE
Office opening hours seem off

### ISSUE THREAD

**Issue by willemvb** [spatie/spatie.be#29]
In the telephone dialog the office seems closed at 10:30 AM

**Comment by brendt** [comment]
The wrong timezone was configured, it should work now!

**Comment by brendt** [comment]
@willemvb did I count it correct, was this on a Wednesday? The hours seem to be correct right now.

**Comment by willemvb** [comment]
Indeed!
<img width="220" alt="screen shot 2018-09-24 at 09 43 31" src="https://user-images.githubusercontent.com/1336390/45941496-b5e30880-bfde-11e8-9dd2-9dbccfc9db6c.png">
