### ISSUE TITLE
Docs site-broken cache or something?

### ISSUE THREAD

**Issue by drbyte** [spatie/spatie.be#290]
This is a cross-post from https://github.com/spatie/laravel-permission/issues/2594 to bring attention to the problem.

Note how the config shows a `v6` linked to `main`:
https://github.com/spatie/spatie.be/blob/main/config/docs.php#L253-L263

But the live site shows no link to v6 AND all indexed links to v6 are redirecting to v5.
<img width="468" alt="Screen Shot 2024-01-21 at 3 24 17 PM" src="https://github.com/spatie/spatie.be/assets/404472/3798b0d5-638e-470b-9f63-b99b9c74efae">

**Comment by vlasscontreras** [comment]
As of today, only `v3` can be accessed on the docs site.

**Comment by freekmurze** [comment]
I've made sure that all versions are now available. I've also temporary disabled the automatic sync (which I suspect is wrecking havoc)
