### ISSUE TITLE
Media library pro repo link 404

### ISSUE THREAD

**Issue by Design2k** [spatie/spatie.be#292]
The link for the repo is not working. 

https://spatie.be/docs/laravel-medialibrary/v11/handling-uploads-with-media-library-pro/installation

![IMG_9645](https://github.com/spatie/spatie.be/assets/94699101/5b4a2d2c-fbe0-41e4-85ba-6505c4cff986)

**Comment by sebastiandedeyne** [comment]
The page displays a 404 because it's a private repository. If you've purchased a license, you can request access from your [purchases](https://spatie.be/profile/purchases) page.
