### ISSUE TITLE
404 error on support us page

### ISSUE THREAD

**Issue by prajwal89** [spatie/spatie.be#307]
While browsing the spatie.be website, I came across this page 
[https://spatie.be/open-source/support-us](https://spatie.be/open-source/support-us) , which gives a 404 error.

This link I found on pages like 
https://spatie.be/docs/laravel-pdf/v1/support-us
https://spatie.be/docs/laravel-medialibrary/v11/support-us

**Comment by sebastiandedeyne** [comment]
Thanks for the heads up!
