### ISSUE TITLE
Tweets should be paced better

### ISSUE THREAD

**Issue by freekmurze** [spatie/spatie.be#36]
Right now we tweet new good first issues immediately. When tagging a lots of issues at once, this results in many simultaneous tweets. This can be perceived as spammy.

<img width="605" alt="screen shot 2018-10-23 at 10 03 43" src="https://user-images.githubusercontent.com/483853/47345763-da98d180-d6ab-11e8-81e3-e89e21b3024b.png">

Let's only tweet out one issue every 2 hours.

**Comment by rubenvanassche** [comment]
This one is solved with PR #37
