### ISSUE TITLE
Packages have wrong download count

### ISSUE THREAD

**Issue by tricki** [spatie/spatie.be#51]
The download count on the packages list always shows the same value as the fork count.

Pretty sure the problem is in [views/livewire/repositories.blade.php#L51](https://github.com/spatie/spatie.be/blob/master/resources/views/livewire/repositories.blade.php#L51) where `$repository->stars` should get replaced with `$repository->downloads`.

**Comment by freekmurze** [comment]
@rubenvanassche can you take a look at this next week?

**Comment by sebastiandedeyne** [comment]
Already done, thanks for mentioning!
