### ISSUE TITLE
Docs integration

### ISSUE THREAD

**Issue by willemvb** [spatie/spatie.be#57]
For the `add-customer-branch`:

### Docs index

- [x] about/docs/guidlines: highlight active menu item in service menu
- [x] reverse sort version numbers (as suggested by @sebastiandedeyne)
- [x] package order: alphabetically?
 
### Docs detail:
- [x] check my dummy breadcrumb code and link second segment to package intro
- [x] check side navigation sections order. 'Introduction' is not always on top
- [x] show big title only on introduction page
- [x] images missing
- [ ] optional: next/prev page link at the bottom
- [x] optional: provide bookmark on each H2
- [x] check side nav version jumper:  set current option active + jump to correct url

**Comment by AlexVanderbist** [comment]
- [ ] Import command schedulen op 2020
