### ISSUE TITLE
It's possible to link a GitHub account to 2 Spatie accounts - last account linked can't login

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/spatie.be#68]
Check if the github account is already linked to an account before linking in profile > link github account

**Comment by freekmurze** [comment]
I think this has been resolved in the latest fix. Could you check this again?

**Comment by AlexVanderbist** [comment]
It's still possible to link a GitHub account to 2 accounts

**Comment by freekmurze** [comment]
I don't think it's likely that this will happen. Closing for now.
